version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=forecasting_db
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/forecasting_db
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=forecasting_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
