services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - "5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npx vite --host 0.0.0.0
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=forecasting_db
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/forecasting_db
    depends_on:
      - db
    command: ./start.sh
    networks:
      - app-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=forecasting_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
